### ISSUE TITLE
Local part of prefixed name may start with colon (:)

### ISSUE THREAD

**Issue by sgoetz-brox** [atextor/owl-cli#5]
`owl write` doesn’t seem to handle a prefixed name’s local part correctly if it starts with `:` (which seems to be an [allowed start character](https://github.com/atextor/owl-cli/issues/4)).

## Test 1

`test_1.ttl`:

```
@prefix ex: <https://example.org/> .

ex::Hello a ex:Test .
```

`owl write test_1.ttl` generates:

```
@prefix ex: <https://example.org/> .

ex: a ex:Test .
```

## Test 2

`test_2.ttl`:

```
@prefix ex: <https://example.org/> .

<https://example.org/:Hello> a <https://example.org/Test> .
```

`owl write test_2.ttl` generates:

```
@prefix ex: <https://example.org/> .

ex: a ex:Test .
````

**Comment by atextor** [comment]
Hi @sgoetz-brox,
yes this looks like a bug. We'll need to see whether this happens during parsing or during writing.
